export const translator = {
    en: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        language: 'Language',
        homepage: "Homepage",
        unitedStatesFlag: 'United States\' Flag',
        spanishFlag: 'Spanish Flag',
        siteNavigation: 'Site Navigation',
        darkMode: 'Dark Mode',
        home: 'Home',
        getInTouch: 'Get In Touch',
        socialMedia: 'Social Media',
        contactUs: 'Contact Us',
        myAccount: 'My Account',
        image: 'Image',
        termsOfService: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',
        refundPolicy: 'Refund and Cancellations Policy',
        refundsAndCancellations: 'Refunds and Cancellations',
        nextImage: 'Next Image',
        previousImage: 'Previous Image',
        close: 'Close',
        email: "Email",
        phoneNumber: "Phone Number",
        yourMessage: "Your Message",
        attachment: "Add an attachment",
        subscribeToNewsletter: "Subscribe to our newsletter",
        preferredContactMethod: "Preferred Contact Method",
        contactInformation: "Contact Information",
        preferToReachOut: "If you prefer to reach out directly, here is our contact information:",
        visitOurOffice: "Visit Our Office",
        comeAndVisit: "Come and visit our office located at:",
        leaveYourReview: 'Leave Your Review',
        writeYourReview: 'Write your review',
        submit: 'Submit',
        sending: 'Sending...',
        searchPlaceholder: 'Search...',
        catalog: 'Catalog',
        ourWork: 'Our Work',
        homeDescription: "",
        catalogSlogan: "Gear Up, Stand Out, Ride On.",
        discount: "off",
        addToCart: "Add to Cart",
        custom: "Custom",
        men: "Men",
        women: "Women",
        selectedOption: "Selected Option",
        quantityUpdated: "Item quantity has been updated.",
        hasBeenAddedToTheCart: "has been added to the cart!",
        hasBeenRemovedFromTheCart: "has been removed from the cart.",
        championsWearRADA: "Champions wear RADA",
        elevateYourTraining: "Elevate your training and racing with cutting-edge design and performance.",
        exploreNow: "Explore Now",
        myCart: "My Cart",
        total: "Total",
        yourCartIsEmpty: "Your cart is empty",
        looksLikeYouHaventMadeYourChoice: "Looks like you haven't made your choice yet...",
        exploreOurCatalog: "Explore our catalog",
        siteDescription: "Premium cycling wear designed for champions in training and racing. Shop our latest releases and enjoy free domestic shipping on orders over $100.",
        checkout: "Checkout",
        subtotal: "Sub Total",
        deliveryFee: "Delivery Fee",
        totalAmount: "Total Amount",
        validate: "Validate",
        enterYourPromoCode: "Enter your promo code",
        price: "Price",
        size: "Size",
        gender: "Gender",
        sortBy: "Sort by",
        clearAllFilters: "Clear All Filters",
        thereAreNoProducts: "There are no products that match your criteria... but hang tight! We're always adding new products that might be just what you're looking for.",
        reviews: "reviews",
        description: "description",
        details: "details",
        thisProductHasNoReviews: "This product has no reviews.",
        decreaseQuantityTo: "decrease quantity to",
        increaseQuantityTo: "increase quantity to",
        itemAdded: "Item Added!",
        similarProducts: "Similar Products",
        productNotFound: "Product not found.",
        cyclistWearingRADA: "Cyclist Wearing Rada Cycling Wear Products",
        newArrivals: "New Arrivals",
        exploreEndlessPossibilities: "Explore endless possibilities and make a statement that's uniquely yours.",
        customDeals: "Custom RADA Deals",
        offerOneBibTwoJerseys: "Offer: 1 Bib Plus 2 Jerseys",
        mostViewed: "Most Viewed",
        shippingInformation: "Shipping Information",
        fullName: "Full Name",
        shippingAddress: "Shipping Address",
        city: "City",
        postalCode: "Postal Code",
        country: "Country",
        quantity: "Quantity",
        totalPrice: "Total Price",
        continue: "Continue",
        thankYouForYourMessage: "Thank you for your message. We will get back to you shortly!",
        customPageDescription: "Discover custom cycling wear crafted to perfection at Rada Cycling Wear. Connect with us to personalize your cycling uniforms with unparalleled quality and design. Experience the blend of innovation and comfort tailored just for you. Start your custom journey today!",
        elevateYourTeamWithCustomDesigns: "Elevate Your Team's Spirit with Custom Designs",
        ifYourLookingForCustom: "If you're looking to get custom-designed cycling uniforms, you're in the right place! Please fill out the form below or email us directly at",
        yourEmail: "Your Email",
        subject: "Subject",
        whyChoose: "Why Choose RADA Cycling Wear?",
        weUnderstand: "We understand the importance of comfort, performance, and style in cycling uniforms. Here's why teams love working with us:",
        reflectTeam: "Custom designs that reflect your team's spirit and ambition.",
        highQualityMaterials: "High-quality materials for enhanced performance and durability.",
        expertAdvice: "Expert advice to help you choose the best options for your needs.",
        logInToRADA: "Log in to RADA",
        password: "Password",
        forgotPassword: "Forgot Password",
        logIn: "Log In",
        dontHaveAnAccount: "Don't have an account?",
        signIn: "Sign In",
        accountPageDescription: "Manage your Rada Cycling Wear profile with ease. Access your orders, track custom cycling wear progress, and update your preferences all in one place. Simplify your cycling journey with personalized account settings. Log in to elevate your experience!",
        ourCraftmanship: "Our Craftsmanship",
        discoverThePassion: "Discover the passion and precision behind each piece of our cycling wear. Explore our gallery of previous works to see the quality and innovation we bring to cyclists worldwide.",
        passwordsDoNotMatch: "Passwords do not match.",
        signInPageDescription: "Sign in to your Rada Cycling Wear account for secure access to your custom cycling wear orders, preferences, and exclusive updates. Experience a seamless connection to your cycling world. Ready for a smoother ride? Sign in now.",
        confirmPassword: "Confirm Password",
        alreadyHaveAnAccount: "Already have an account?",
        createAnAccount: "Create an account",
        meetRADA: "Meet Rada Cycling Wear",
        experienceTheThrill: "Experience the thrill of cycling with RADA, where performance meets style. Our premium cycling wear is crafted from the finest fabrics, providing the perfect blend of comfort and performance on every ride.",
        mostPopular: "Most Popular.",
        latestReleases: "Latest Releases.",
        yourSatisfaction: "Your satisfaction is our promise!",
        swiftFreeShipping: "Swift, Free Domestic Shipping",
        enjoySeemless: "Enjoy seamless and complimentary shipping on all domestic orders.",
        worryFreeReturns: "Worry-Free 30-Day Returns",
        mindPeaceMatters: "Your peace of mind matters - our hassle-free returns ensure your complete satisfaction.",
        effortlessExchanges: "Effortless Instant Exchanges",
        needADifferentSize: "Need a different size? Experience quick and easy exchanges for the perfect fit.",
        myOrders: "My Orders",
        emptyOrderList: "Your order history is empty.",
        logOut: "Log Out",
        shopNow: "Shop Now",
        someOfOurCustomWork: "Some Of Our Custom Work",
        viewMore: "View more",
        anErrorHasOccurred: "An error has occurred...",
        pleaseSelectASize: "Please select a size",
        viewNewCollection: "View new collection",
        newCollection: "New collection",
        collection: "Collection",
        dataPolicyNotAccepted: "The Data Processing Policy has not been accepted.",
        iAcceptThe: "I accept the",
        dataPolicy: "Data Processing Policy.",
        belongToClubOrOrganization: "Do you belong to a club or organization?",
        completeFormForDiscount: "Complete this form to get your discount.",
        discountOnNextPurchase: "50% off your next purchase",
        success: "Success!",
        informationSubmitted: "Your information has been successfully submitted. You will receive 50% off your next purchase.",
        clubName: "Club Name",
        male: "Male",
        female: "Female",
        other: "Other",
        firstName: "First Name",
        lastName: "Last Name",
        whyUsTitle: "RADA Custom",
        whyUsDescription: "We understand the importance of comfort, performance, and style in cycling apparel. The RADA Custom Department will help bring your ideas to life and design your dream kit for your team, club or event.",
        highQualityProducts: "High-quality products crafted from the finest European fabrics.",
        lowMinimumKits: "Low minimum (6 kits per design).",
        turnAroundTime: "Production time of six weeks.",
        bestChoice: "RADA is your best choice for custom cycling apparel. Contact us now to start making your vision a reality!",
        teamName: "Team Name",
        teamClubSize: "Team / Club Size",
        message: "Message",
        howDidYouHearAboutUs: "How did you hear about RADA Cycling Wear Custom Apparel?",
        optional: "Optional",
        invalidPhoneNumber: "Invalid Phone Number",
        contactByEmail: 'Email',
        contactByWhatsApp: 'WhatsApp',
        goToCart: "Go to Cart",
        thankYouForYourPurchase: "Thank you for your purchase!",
        orderPlacedMessage: "Your order has been successfully placed. You will receive a confirmation email shortly.",
        returnToHome: "Return to Home",
        cartItemPurchased: "Cart item purchased",
        orderPlacedTitle: "Order Placed!",
        admin: 'Admin',
    },
    es: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        language: 'Idioma',
        homepage: "Página de Inicio",
        unitedStatesFlag: 'Bandera de los Estados Unidos',
        spanishFlag: 'Bandera Española',
        siteNavigation: 'Navegación del Sitio',
        darkMode: 'Modo Oscuro',
        home: 'Inicio',
        getInTouch: 'Ponte en Contacto',
        socialMedia: 'Redes Sociales',
        myAccount: 'Mi Cuenta',
        contactUs: 'Contáctanos',
        image: 'Imagen',
        termsOfService: 'Términos de Servicio',
        privacyPolicy: 'Política de Privacidad',
        refundPolicy: 'Política de Reembolso y Cancelaciones',
        refundsAndCancellations: 'Reembolsos y Cancelaciones',
        nextImage: 'Ver Imagen Siguiente',
        previousImage: 'Ver Imagen Previa',
        close: 'Cerrar',
        email: "Correo Electrónico",
        phoneNumber: "Número de Teléfono",
        yourMessage: "Tu Mensaje",
        attachment: "Añadir un adjunto",
        subscribeToNewsletter: "Suscríbete a nuestro boletín",
        preferredContactMethod: "Método de Contacto Preferido",
        contactInformation: "Información de Contacto",
        preferToReachOut: "Si prefieres comunicarte directamente, aquí está nuestra información de contacto:",
        visitOurOffice: "Visita Nuestra Oficina",
        comeAndVisit: "Ven y visita nuestra oficina ubicada en:",
        leaveYourReview: 'Deja tu Reseña',
        writeYourReview: 'Escribe tu reseña',
        submit: 'Enviar',
        sending: 'Enviando...',
        searchPlaceholder: 'Buscar...',
        catalog: 'Catálogo',
        ourWork: 'Nuestro trabajo',
        homeDescription: "",
        catalogSlogan: "Viste para Impresionar, Pedalea para Triunfar.",
        discount: "de descuento",
        addToCart: "Añadir al carrito",
        custom: "Custom",
        men: "Hombres",
        women: "Mujeres",
        selectedOption: "Opción seleccionada",
        quantityUpdated: "Los cambios han sido guardados.",
        hasBeenAddedToTheCart: "ha sido agregado al carrito!",
        hasBeenRemovedFromTheCart: "ya no está en tu carrito.",
        championsWearRADA: "Los campeones usan RADA.",
        elevateYourTraining: "Eleva tu entrenamiento y competencias con un diseño y rendimiento innovadores.",
        exploreNow: "Explorar",
        myCart: "Carrito",
        total: "Total",
        yourCartIsEmpty: "Tu carrito está vacío",
        looksLikeYouHaventMadeYourChoice: "Parece que aún no has hecho tu elección...",
        exploreOurCatalog: "Explora nuestro catálogo",
        siteDescription: "Ropa de ciclismo de primera calidad diseñada para campeones en entrenamiento y competición. Compra nuestros últimos lanzamientos y disfruta del envío gratuito a nivel nacional en pedidos superiores a $100.",
        checkout: "Continuar",
        subtotal: "Subtotal",
        deliveryFee: "Costo de envío",
        totalAmount: "Monto Total",
        validate: "Validar",
        enterYourPromoCode: "Ingresa tu código promocional",
        price: "Precio",
        size: "Talla",
        gender: "Género",
        sortBy: "Ordenar por",
        clearAllFilters: "Reiniciar filtros",
        thereAreNoProducts: "No hay productos que coincidan con tus criterios... ¡pero espera! Siempre estamos añadiendo nuevos productos que podrían ser justo lo que buscas.",
        reviews: "reseñas",
        description: "descripción",
        details: "detalles",
        thisProductHasNoReviews: "Este producto no tiene reseñas.",
        decreaseQuantityTo: "disminuir la cantidad a",
        increaseQuantityTo: "aumentar la cantidad a",
        itemAdded: "¡Producto añadido!",
        similarProducts: "Productos similares",
        productNotFound: "Producto no encontrado.",
        cyclistWearingRADA: "Ciclista usando productos de Rada Cycling Wear",
        newArrivals: "Novedades",
        exploreEndlessPossibilities: "Explora posibilidades infinitas y haz una declaración que sea únicamente tuya.",
        customDeals: "Ofertas personalizadas de RADA",
        offerOneBibTwoJerseys: "Oferta: 1 Babero más 2 Camisetas",
        mostViewed: "Más Vistos",
        shippingInformation: "Información de envío",
        fullName: "Nombre completo",
        shippingAddress: "Dirección de envío",
        city: "Ciudad",
        postalCode: "Código postal",
        country: "País",
        quantity: "Cantidad",
        totalPrice: "Precio total",
        continue: "Continuar",
        thankYouForYourMessage: "Gracias por tu mensaje. ¡Te responderemos pronto!",
        customPageDescription: "Descubre ropa de ciclismo personalizada elaborada a la perfección en Rada Cycling Wear. Conéctate con nosotros para personalizar tus uniformes de ciclismo con calidad y diseño sin igual. Experimenta la combinación de innovación y comodidad hecha especialmente para ti. ¡Inicia tu viaje personalizado hoy!",
        elevateYourTeamWithCustomDesigns: "Eleva el espíritu de tu equipo con diseños personalizados",
        ifYourLookingForCustom: "Si buscas uniformes de ciclismo diseñados a medida, ¡estás en el lugar correcto! Por favor, completa el formulario a continuación o envíanos un correo electrónico directamente a",
        yourEmail: "Tu correo electrónico",
        subject: "Asunto",
        whyChoose: "¿Por qué elegir RADA Cycling Wear?",
        weUnderstand: "Entendemos la importancia del confort, rendimiento y estilo en los uniformes de ciclismo. Aquí te explicamos por qué los equipos adoran trabajar con nosotros:",
        reflectTeam: "Diseños personalizados que reflejan el espíritu y la ambición de tu equipo.",
        highQualityMaterials: "Materiales de alta calidad para un rendimiento mejorado y durabilidad.",
        expertAdvice: "Asesoramiento experto para ayudarte a elegir las mejores opciones según tus necesidades.",
        logInToRADA: "Iniciar sesión en RADA",
        password: "Contraseña",
        forgotPassword: "¿Olvidaste tu contraseña?",
        logIn: "Iniciar sesión",
        dontHaveAnAccount: "¿No tienes cuenta?",
        signIn: "Registrarse",
        accountPageDescription: "Administra tu perfil de Rada Cycling Wear con facilidad. Accede a tus pedidos, sigue el progreso de tu ropa de ciclismo personalizada y actualiza tus preferencias, todo en un solo lugar. Simplifica tu viaje ciclista con ajustes de cuenta personalizados. ¡Inicia sesión para elevar tu experiencia!",
        ourCraftmanship: "Nuestro Trabajo",
        discoverThePassion: "Descubre la pasión y precisión detrás de cada pieza de nuestra ropa de ciclismo. Explora nuestra galería de trabajos anteriores para ver la calidad e innovación que ofrecemos a ciclistas en todo el mundo.",
        passwordsDoNotMatch: "Las contraseñas no coinciden.",
        signInPageDescription: "Inicia sesión en tu cuenta de Rada Cycling Wear para un acceso seguro a tus pedidos de ropa de ciclismo personalizada, preferencias y actualizaciones exclusivas. Experimenta una conexión fluida con tu mundo ciclista. ¿Listo para un paseo más suave? Inicia sesión ahora.",
        confirmPassword: "Confirmar contraseña",
        alreadyHaveAnAccount: "¿Ya tienes una cuenta?",
        createAnAccount: "Crea una cuenta",
        meetRADA: "Conoce Rada Cycling Wear",
        experienceTheThrill: "Experimenta la emoción de ciclismo con RADA, donde el rendimiento se encuentra con el estilo. Nuestra ropa de ciclismo premium está usa los tejidos más finos, proporcionando la combinación perfecta de comodidad y rendimiento en cada paseo.",
        mostPopular: "Más Popular.",
        latestReleases: "Últimos Lanzamientos.",
        yourSatisfaction: "¡Tu satisfacción es nuestra promesa!",
        swiftFreeShipping: "Envío Doméstico Rápido y Gratuito",
        enjoySeemless: "Disfruta de envíos nacionales rápidos y gratuitos en todos los pedidos.",
        worryFreeReturns: "Devoluciones Sin Preocupaciones de 30 Días",
        mindPeaceMatters: "Tu tranquilidad es importante: nuestras devoluciones sin complicaciones aseguran tu completa satisfacción.",
        effortlessExchanges: "Intercambios Instantáneos Sin Esfuerzo",
        needADifferentSize: "¿Necesitas una talla diferente? Experimenta intercambios rápidos y fáciles para el ajuste perfecto.",
        myOrders: "Mis Pedidos",
        emptyOrderList: "Tu historial de pedidos está vacío.",
        logOut: "Cerrar Sesión",
        shopNow: "Explorar",
        someOfOurCustomWork: "Algunos de Nuestros Trabajos Personalizados",
        viewMore: "Ver más",
        anErrorHasOccurred: "Ha ocurrido un error...",
        pleaseSelectASize: "Por favor selecciona una talla",
        viewNewCollection: "Ver nueva colección",
        newCollection: "Nueva colección",
        collection: "Colección",
        dataPolicyNotAccepted: "La Política de tratamiento de datos no ha sido aceptada.",
        iAcceptThe: "Acepto la",
        dataPolicy: "Política de tratamiento de datos.",
        belongToClubOrOrganization: "¿Perteneces a un club u organización?",
        completeFormForDiscount: "Completa este formulario para obtener tu descuento.",
        discountOnNextPurchase: "50% de descuento en tu próxima compra",
        success: "¡Hecho!",
        informationSubmitted: "Tu información ha sido enviada con éxito. Recibirás 50% en tu próxima compra.",
        clubName: "Nombre del club",
        male: "Masculino",
        female: "Femenino",
        other: "Otro",
        firstName: "Nombre",
        lastName: "Apellido",
        whyUsTitle: "RADA Custom",
        whyUsDescription: "Entendemos la importancia de la comodidad, el rendimiento y el estilo en la ropa de ciclismo. El Departamento Custom de RADA te ayudará a hacer realidad tus ideas y diseñar el uniforme de tus sueños para tu equipo, club o evento.",
        highQualityProducts: "Productos de alta calidad fabricados con las mejores telas europeas.",
        lowMinimumKits: "Mínimo (6 kits por diseño).",
        turnAroundTime: "Tiempo de entrega de 6 semanas desde la producción hasta la entrega.",
        bestChoice: "RADA es tu mejor opción para ropa de ciclismo personalizada. ¡Contáctanos ahora para empezar a hacer realidad tu visión!",
        teamName: "Nombre del equipo",
        teamClubSize: "Tamaño del equipo / club",
        message: "Mensaje",
        howDidYouHearAboutUs: "¿Cómo te enteraste de la ropa personalizada de RADA Cycling Wear?",
        optional: "Opcional",
        invalidPhoneNumber: "Número de teléfono inválido",
        contactByEmail: 'Correo electrónico',
        contactByWhatsApp: 'WhatsApp',
        goToCart: "Ir al Carrito",
        thankYouForYourPurchase: "¡Gracias por tu compra!",
        orderPlacedMessage: "Tu pedido ha sido realizado con éxito. Recibirás un correo electrónico de confirmación en breve.",
        returnToHome: "Volver a Inicio",
        cartItemPurchased: "Artículo del carrito comprado",
        orderPlacedTitle: "¡Pedido Realizado!",
        admin: 'Administrador',
    },
};